### ISSUE TITLE
Update tag files on change

### ISSUE THREAD

**Issue by adelbertc** [ceedubs/sbt-ctags#12]
Just a thought I had, no clue how possible it is, but wondering if we can somehow update tag files on change.. presumably SBT knows which file has changed and needs to recompile.. maybe we can hook into that or something and re-generate/update the tags file.. somehow.

**Comment by stew** [comment]
if we did know what file just changed, would we be able to update the tags file? I have a feeling we don't know what things to delete from the tags file before we update it.

**Comment by adelbertc** [comment]
My best guess thus far is if we have 1 tag file per sub-project, then whenever a file in a sub-project changes we just re-generate for that project. Pretty naive, though I'm not sure we can reach into a tag file and re-generate source-file-specific tags.

**Comment by stew** [comment]
it's a non-issue for me, emacs notices this :)

**Comment by NightWhistler** [comment]
This is a basic SBT feature: you can just run `sbt ~genCtags` to have it watch for file changes.
