### ISSUE TITLE
Allow relative filenames

### ISSUE THREAD

**Issue by raboof** [ceedubs/sbt-ctags#13]
sbt-ctags invokes ctags with absolute directory names. This causes ctags to use absolute filenames in the .tags file, too.

Some applications don't support absolute filenames in tags files, so it would be nice if sbt-ctags supported generating using relative directory names when invoking ctags.

https://github.com/atom/symbols-view/issues/108

**Comment by raboof** [comment]
Hmm, reading http://ctags.sourceforge.net/FORMAT:

```
The name of the file where {tagname} is defined, relative to the current directory (or location of the tags file?).
```

So arguably this is a ctags bug...

**Comment by ceedubs** [comment]
> So arguably this is a ctags bug...

@raboof do you mean an sbt-ctags bug? If so, then I think you are probably right.

A pull request (by you or anyone else) would be welcome. I'd love for some improvements (such as this one) to get into sbt-ctags, but currently my main focus is on other projects.

**Comment by fedragon** [comment]
I just added the option to generate relative paths on demand :)

**Comment by fedragon** [comment]
@ceedubs I opened a pull request to address this issue, could you take a look at it? :)

**Comment by NightWhistler** [comment]
Closing this since it's been implemented.
