### ISSUE TITLE
dot is prepended to filename

### ISSUE THREAD

**Issue by fommil** [ceedubs/sbt-ctags#23]
even with

```scala
net.ceedubs.sbtctags.CtagsKeys.ctagsParams ~= (default => default.copy(tagFileName = "TAGS", extraArgs = "-e" +: default.extraArgs))
```

the generated file is in `.TAGS` (note the dot) because of this line

https://github.com/ceedubs/sbt-ctags/blob/master/src/main/scala/net/ceedubs/sbtctags/SbtCtags.scala#L128

workaround is to manually move the file after creation. This can all, be scripted, of course.

**Comment by fommil** [comment]
*sigh* no it can't really be scripted because the `sbt-command` is async... would you be open to changing the default to have the `.` in the name?

```elisp
(defun sbt-ctags ()
  (interactive)
  (sbt:command "genCtags")
  (sleep-for 5)
  (rename-file (concat (projectile-project-root) ".TAGS")
               (concat (projectile-project-root)) "TAGS"))
```

**Comment by apetresc** [comment]
Any reason why this is closed? I also have the same request :(
